Add new status selector
dansenpir/owlrangenotes-frontend pull request #17
Opened 2022-10-28 00:29 UTC by mateusdegobi

https://user-images.githubusercontent.com/17092357/198421769-281fb2fc-7d94-4195-8d9b-71be1bd500cb.mov

![image](https://user-images.githubusercontent.com/17092357/198421827-3d98f90a-d5e0-4f3a-91ec-89ffc8f2c8bc.png)

2022-10-28 13:17 UTC, felpfsf approved these changes, later dismissed
Aprovado

2022-10-31 11:38 UTC, dansenpir requested changes

2022-10-31 11:38 UTC, dansenpir commented on src/components/SelectStatus/components/ItemDropDown/index.tsx
> +  const handleOnClick = () => onChangeValue(item);
Necessário refatorar este trecho de código.

https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

2022-11-08 02:58 UTC, felpfsf submitted a review, later dismissed
LGTM

2022-11-08 10:42 UTC, mateusdegobi commented
![image](https://user-images.githubusercontent.com/17092357/200543414-b518fae1-9dcd-4647-802d-4d0d1a5df385.png)
Subi o commit errado da outra PR e nem reparei. O eslint não estava me deixando commitar pela regra e tive que corrigir.
vou dar o rebase HEAD e dou o push no commit certo assim que eu chegar em casa.

2022-11-09 09:51 UTC, mateusdegobi reviewed
Ok, pra mim parece certo.

2022-11-09 09:58 UTC, dansenpir approved these changes, later dismissed
LGTM

2022-11-09 13:33 UTC, viniciuscosmome submitted a review, later dismissed
👍

2022-11-11 14:40 UTC, dansenpir approved these changes
LGTM

2022-11-11 14:40 UTC, merged