[Feat][components] - Form Adicionar Material de estudo
dansenpir/owlrangenotes-frontend pull request #8
Opened 2022-10-21 18:49 UTC by felpfsf

### Feat
#### O componente de formulário para Adicionar material de estudo
![image](https://user-images.githubusercontent.com/2619027/197263549-5f8f1910-30e5-450e-99e7-1e9b95ec8e9e.png)

#### Demonstração:
![owlrangenotes_form_add_material](https://user-images.githubusercontent.com/2619027/197263749-3548c187-b3e7-451e-b2b7-c32e7eabd889.gif)
![owlrangenotes_form_add_material_2](https://user-images.githubusercontent.com/2619027/197263754-bebeda72-f55a-463e-979b-cc1d79aace0e.gif)

Ele envia um objeto contendo os dados do formulário, deixei de acordo com a nomenclatura do backend. 

O método post está adicionado no código mas está comentado por não ter o endpoint, no lugar do alert com a mensagem de sucesso/erro tb seria substituído pelo modal.
![image](https://user-images.githubusercontent.com/2619027/197265908-65fc8589-4215-4078-864f-67c5afb55959.png)

#### Responsividade
Sem breakpoints, os componentes se ajustam automaticamente com a tela, no exemplo abaixo eu reduzo a resolução de 320px e ele chega a máxima de 800px, acho que torna compatível com vários dispositivos.
![owlrangenotes_form_add_material_3](https://user-images.githubusercontent.com/2619027/197264671-b41e0be6-7d46-4b8b-9372-7c2c44009504.gif)

Minhas dúvidas: O select de pastas está sendo mockado para testes, esses dados virão do backend, certo? Em outro componente o usuário vai criar essas pastas, é dessa forma que vai funcionar?

2022-10-21 19:01 UTC, dansenpir requested changes

2022-10-21 19:01 UTC, dansenpir commented on src/components/AddMaterialForm/index.tsx
> +    // }
Não é uma boa prática comentar o código.

2022-10-21 19:02 UTC, dansenpir approved these changes, later dismissed

2022-10-21 20:22 UTC, viniciuscosmome requested changes

2022-10-21 20:22 UTC, viniciuscosmome commented on src/components/AddMaterialForm/index.tsx
> +// Components
Linha 4 e 7:
Estes dois comentários são desnecessários

2022-10-21 20:22 UTC, viniciuscosmome commented on src/components/AddMaterialForm/ui/Button/Button.Style.ts
> +  ${(props: { isCancelVariant: any }) => props.isCancelVariant && cancelButton}
A correção deste código é um pouco mais longa, você pode criar uma `interface` ou um `type` e atribuir a ele os atributos que a `props`  irá receber.

```
interface IProps {
  isCancelVariant: boolean;
}
```

em seguida, você pode atribuir esta nova interface a sua `props`:

```suggestion
  ${(props: IProps) => props.isCancelVariant && cancelButton}
```

---
**(Modificação opcional)**
Além dessas alterações, você também pode usar o `destructuring`, não é obrigatório:

```suggestion
  ${({isCancelVariant}: IProps) => isCancelVariant && cancelButton}
```

2022-10-21 20:41 UTC, felpfsf commented on .eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "off",
Acho que isso foi feito no começo do projeto, na primeira alteração do @VicenteCarlos 
https://github.com/dansenpir/owlrangenotes-frontend/blob/feature/home-page/.eslintrc.json

2022-10-21 20:51 UTC, felpfsf commented on src/components/AddMaterialForm/index.tsx
> +// Components
removi os comentários

2022-10-21 20:53 UTC, viniciuscosmome commented on .eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "off",
ah sim, compreeendi

2022-10-21 20:55 UTC, felpfsf commented on src/components/AddMaterialForm/ui/Button/Button.Style.ts
> +  ${(props: { isCancelVariant: any }) => props.isCancelVariant && cancelButton}
No Button.tsx eu já tem a interface 
![image](https://user-images.githubusercontent.com/2619027/197285592-23d545c1-800b-4f91-9e22-1e8576e64a62.png)
e está importada no arquivo de estilo para poder usar a prop da variante
![image](https://user-images.githubusercontent.com/2619027/197286951-f6b6d491-5a2f-49e6-8501-35f5ac83ab69.png)

Aí só fiz a alteração destruturando como vc sugeriu
![image](https://user-images.githubusercontent.com/2619027/197286515-4a6b36b6-b59c-45d9-b757-9f43380fb160.png)

2022-10-21 21:10 UTC, viniciuscosmome approved these changes

2022-10-21 23:55 UTC, mateusdegobi commented on src/components/AddMaterialForm/ui/Button/Button.tsx
> +    <>
qual seria a utilidade do fragment neste caso? (pergunta não irônica)

2022-10-22 00:07 UTC, felpfsf commented on src/components/AddMaterialForm/ui/Button/Button.tsx
> +    <>
Eu tinha uma outra ideia de colocar uma msg mas acabei deixando de lado ela

2022-10-22 00:18 UTC, mateusdegobi approved these changes

2022-10-22 15:51 UTC, merged